name: Validate dev-bio

on:
  push:
    branches:
      - dev-bio

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --platform linux/amd64 .
