name: Validate dev-bio

on:
  push:
    branches:
      - dev-bio

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - run: docker build --platform linux/amd64 .
